server:
  port: 1001

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/grand_blue?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver: dev.miku.r2dbc.mysql.MySqlConnection
    name: grand_blue
    pool:
      initial-size: 3
      max-size: 5